# Manipulate PyTorch Tensors
<hr>

## Matrix manipulation

In [2]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [3]:

# write your code here

A = torch.tensor([[1, 2],
          [3, 4]])
B = torch.tensor([[10, 20],
          [30, 40]])
C = torch.add(A, B)

# print
print(A)
print('')
print(B)
print('')
print(C)

tensor([[1, 2],
        [3, 4]])

tensor([[10, 20],
        [30, 40]])

tensor([[11, 22],
        [33, 44]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [4]:

# write your code here

print(A.dim())    # print the dimension of the matrix A
print('')
print(A.size())    # print the size of the matrix A
print('')
print(A.type())    # print the type of the matrix A

2

torch.Size([2, 2])

torch.LongTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [6]:

# write your code here
A = A.int()
A_long = A.long()

print(A_long.type())    # print the type of A_long
print('')
print(A.type())    # print the type of A

torch.LongTensor

torch.IntTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [7]:

# write your code here

A = torch.rand(5,2,3)

print(A)
print(A.type())    # print the type of A
print(A.dim())    # print the dimension of A
print(A.size() )    # print the size of A
print(A.size()[1])    # print the size of the middle (second) dimension

tensor([[[0.9891, 0.7372, 0.3474],
         [0.1693, 0.6599, 0.4323]],

        [[0.2313, 0.7767, 0.2328],
         [0.2236, 0.8772, 0.1210]],

        [[0.7667, 0.8562, 0.4763],
         [0.3311, 0.2802, 0.0316]],

        [[0.1119, 0.5138, 0.3711],
         [0.7996, 0.7951, 0.3525]],

        [[0.6619, 0.6157, 0.1136],
         [0.2158, 0.6711, 0.2810]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [10]:

# write your code here

A = torch.zeros(2,3,4,5)

print(A)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
