# Manipulate PyTorch Tensors
<hr>

## Matrix manipulation

In [3]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [6]:

# write your code here

A = torch.tensor([[1, 2],
          [3, 4]])
B = torch.tensor([[10, 20],
          [30, 40]])
C = torch.add(A, B)

# print
print(A)
print('')
print(B)
print('')
print(C)

tensor([[1, 2],
        [3, 4]])

tensor([[10, 20],
        [30, 40]])

tensor([[11, 22],
        [33, 44]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [7]:

# write your code here

print(A.dim())    # print the dimension of the matrix A
print('')
print(A.size())    # print the size of the matrix A
print('')
print(A.type())    # print the type of the matrix A

2

torch.Size([2, 2])

torch.LongTensor


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [8]:

# write your code here

A_long = A.long()

print(A_long.type())    # print the type of A_long
print('')
print(A.type())    # print the type of A

torch.LongTensor

torch.LongTensor


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [9]:

# write your code here

A = torch.rand(5,2,3)

print(A)
print(A.type())    # print the type of A
print(A.dim())    # print the dimension of A
print(A.size() )    # print the size of A
print( )    # print the size of the middle (second) dimension

tensor([[[0.4294, 0.6741, 0.2446],
         [0.6366, 0.2799, 0.2676]],

        [[0.8424, 0.8617, 0.9798],
         [0.4206, 0.0355, 0.3402]],

        [[0.5761, 0.3031, 0.9015],
         [0.4892, 0.7903, 0.3244]],

        [[0.9232, 0.1770, 0.3598],
         [0.0608, 0.7237, 0.1336]],

        [[0.5164, 0.9802, 0.2851],
         [0.2879, 0.4731, 0.7010]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])



### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [10]:

# write your code here

A = torch.zeros(2,3,4,5)

print(A)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
